### ISSUE TITLE
Miscompare error reported during the main memory test

### ISSUE THREAD

**Issue by kyewonh** [stressapptest/stressapptest#53]
this means memory error ? 
exected & read data are 64bit and this 64bit  means one of 64 bit data in DIMM ?

2017/11/01-07:14:02(PDT) Status: FAIL - test discovered HW problems
2017/11/01-05:32:30(PDT) Report Error: miscompare : DIMM Unknown : 1 : 23136s
2017/11/01-05:32:30(PDT) Page Error: miscompare on CPU 21(0xFFFFFFFFFFFFFFFFFFFFFFFFFFFF) at 0x7f887275d000(0x442715d000:DIMM Unknown): read:0xaaaaaaa8aaaaaaa8, reread:0xaaaaaaa8aaaaaaa8 expected:0xffffffffffffffff
2017/11/01-05:32:30(PDT) Report Error: miscompare : DIMM Unknown : 1 : 23136s
2017/11/01-05:32:30(PDT) Page Error: miscompare on CPU 21(0xFFFFFFFFFFFFFFFFFFFFFFFFFFFF) at 0x7f887275d008(0x442715d008:DIMM Unknown): read:0xaaaaaaa8aaaaaaa8, reread:0xaaaaaaa8aaaaaaa8 expected:0xffffffffffffffff

**Comment by nickjsanders** [comment]
Typically this means that there was a transaction error, and the DIMM
didn't receive the write, and what you've read is stale data. Yes, the data
is read as (uint64*) so if all the bits of "read" and "expected" are
different, it means they all miscompared.

The most common one here is that a cacheline-size block of data is
corrupted. However, I see "Page Error" which indicates that you have had
very many miscomparing words. I've seen similar issues where the DIMM PLL
became unlocked and simply ignored transactions for awhile, or when there
was address aliasing either due to a pagetable bug or broken address bits.

**Comment by kyewonh** [comment]
thanks for explanation . it is very helpful.  One more question, CPU 21 means the number of CPU core ?

**Comment by nickjsanders** [comment]
It does. It comes from sched_getcpu(), so it will use whatever numbering
glibc uses.

**Comment by kyewonh** [comment]
I appreciated it.
